// <auto-generated />
using System;
using DialectWords.Brokers.Storages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DialectWords.Migrations
{
    [DbContext(typeof(StorageBroker))]
    [Migration("20231217120659_CreateWordsTeble")]
    partial class CreateWordsTeble
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DialectWords.Models.Foundations.words.Word", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdabiyTil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Antonim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IngilizTilida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Misollar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Omonim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OzlashganQatlam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RusTilida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShevaIzohi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sinonim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transkripsiya")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transliteratsiya")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Turkum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
